# Generated by Django 5.2.8 on 2025-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('upc', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
